spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://allinone.cn5daduvgses.us-east-1.rds.amazonaws.com:3306/taskify
    username: admin
    password: Admin1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: #username for "email notification (write email that you will send email to user with this email)"
    password: #password for "email notification"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
    root: info
    group.aist.mam: debug
  file:
    name: ./logs/mam.log


